export const GameConfigs = {
    MAX_IMPULSE: 10,
    MAX_KNOCK:3,
    MAX_RAM_DAMAGE:100,
    GRAVITATION:1,
    IMPACT_MUL:3,
    DENSITY:5,
    BLOOM_LAYER:1,
    SKYBOX_RADIUS:1000,
    MOB_CAP:6,
    SPAWN_CD: 30
}